class VideoModel {
  String videoUrl;
  String thumb_url;

  VideoModel(this.videoUrl, this.thumb_url);
}

List<VideoModel> video = videoList
    .map((item) => VideoModel(item['videoUrl'], item['thumb_url']))
    .toList();
List<Map<String, dynamic>> videoList = [
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
  {
    "videoUrl":
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "thumb_url":
        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Bbb-splash.png",
  },
];
